# Generated by Django 6.0.2 on 2026-02-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_property_bathrooms_alter_property_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
    ]
